version: '3'
services:
  redis:
    image: redis
    container_name: redis31
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
    volumes:
      - ./vol:/vol
    command: 'sh /vol/a.sh'