version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    environment:
      - 'REDIS_PASSWORD=test'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    environment:
      - 'REDIS_PASSWORD=test'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'REDIS_PASSWORD=test'
      - 'REDISCLI_AUTH=test'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'
